swagger: "2.0"
info:
  title: Admin
  description: The master control for the entire project.
definitions:
  Question:
    type: object
    required:
      - questionId
      - questionText
      - domain
      - difficultyLevel
      - correctOption
      - options
    properties:
      questionId:
        type: string
      questionText:
        type: string
      domain:
        type: string
      options:
        type: object
        properties:
          FirstOption:
            type: string
          SecondOption:
            type: string
          ThirdOption:
            type: string
          FourthOption:
            type: string
      difficultyLevel:
        type: integer
      conceptTags:
        type: array
        items:
          type: string
      correctOption:
        type: object
        properties:
          SingleCorrect:
            type: string

paths:
  /questions:
    get:
      description: Gets all the question which needs to be delivered to user.
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/definitions/Question'
    post:
      description: Adds a new question.
      parameters:
      - in: body
        name: Question
        required: true
        schema:
          type: object
          properties:
            questionText:
              type: string
            domain:
              type: string
            options:
              type: object
              properties:
                FirstOption:
                  type: string
                SecondOption:
                  type: string
                ThirdOption:
                  type: string
                FourthOption:
                  type: string
            difficultyLevel:
              type: integer
            correctOption:
              type: object
              properties:
                SingleCorrect:
                  type: string
      responses:
        201:
          description: Created
        404:
          description: Not Found

  /questions/{difficultyLevel}:
    get:
      description: Gets all the question of specific difficulty.
      parameters:
      - in: path
        name: difficultyLevel
        required: true
        schema:
            type: integer
            minimum: 1
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/definitions/Question'
  /questions/{domain}:
    get:
      description: Gets all the question of specific domain.
      parameters:
      - in: path
        name: domain
        required: true
        schema:
            type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Question'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/definitions/Question'

              
              
              



